train: c:\Users\hp\Desktop\pest-detection-starter\Pest detection\train
val: c:\Users\hp\Desktop\pest-detection-starter\Pest detection\valid
test: c:\Users\hp\Desktop\pest-detection-starter\Pest detection\test

# Make sure your nc and names are correct
nc: 12
names: ['Ants', 'Bees', 'Beetles', 'Caterpillars', 'Earthworms', 'Earwigs', 'Grasshoppers', 'Moths', 'Slugs', 'Snails', 'Wasps', 'Weevils']
