train: C:\Users\hp\Downloads\pest-detection-starter\pest-detection-starter\Pest detection -YOLOv8-.v3i.yolov8\train
val: C:\Users\hp\Downloads\pest-detection-starter\pest-detection-starter\Pest detection -YOLOv8-.v3i.yolov8\valid
test: C:\Users\hp\Downloads\pest-detection-starter\pest-detection-starter\Pest detection -YOLOv8-.v3i.yolov8\test

# Make sure your nc and names are correct
nc: 12
names: ['Ants', 'Bees', 'Beetles', 'Caterpillars', 'Earthworms', 'Earwigs', 'Grasshoppers', 'Moths', 'Slugs', 'Snails', 'Wasps', 'Weevils']